<div class="pure-g">
    <div class="pure-u-1 pure-u-xl-1-5"></div>
    <div class="pure-u-1 pure-u-xl-3-5 main-view">
        <div class="pure-u-1">
            <div class="pure-u-1 gif-list-title-pane">
                <div class="gif-list-title">
                    add new category!
                </div>
            </div>
        </div>
        <div class="pure-u-1" style="color: #984B43">
            <p></p>
            <form method="post" class="pure-form pure-form-aligned">
                <fieldset>
                    <div class="pure-control-group">
                        <label for="name" class="pure-input-1-2">name</label>
                        <input id="name" class="pure-input-1-2" type="text" value="<?php echo $name;?>" name="name"  placeholder="Name">
                    </div>
                    <div class="pure-control-group">
                        <label for="color" class="pure-input-1-2">color</label>
                        <select id="color" name="colorCode" class="pure-input-1-2">
                            <?php foreach($colors as $key=>$value): ?>
                                <option value="<?php echo $value; ?>"><?php echo $key; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="pure-controls">
                        <input id="saveForm" class="pure-button add-button" type="submit" name="submit" value="add category!" />
                    </div>

                </fieldset>
            </form>
        </div>
        <div class="pure-u-1 pure-u-xl-1-5"></div>
    </div>

</div>