<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Add Category</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 30px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1><a href="/">gif.lib</a> | <a href="/gif/add/test">add GIF</a> |<a href="/categories">categories</a> </h1>
<h1>Add Category</h1>
<form method="post">
<p>Name:</p>
<input type="text" name="name" value="<?php echo $name;?>">


<p>Color:</p>
<select name="colorCode" >
    <?php foreach($colors as $key=>$value): ?>
            <option value="<?php echo $value; ?>"><?php echo $key; ?></option>
    <?php endforeach; ?>
</select>
<p></p>
<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
</form>
</body>
</html>