<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Add GIF</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 30px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1><a href="/">gif.lib</a> | <a href="/gif/add/test">add GIF</a> |<a href="/categories">categories</a> </h1>
<h1>Add GIF</h1>
<form method="post" enctype="multipart/form-data">
    <p>File:</p>
    <input type="file" name="bytes"">
    <p>Description:</p>
    <input type="text" name="description" value="<?php echo $description;?>">


    <p>Category:</p>
    <select name="category_id" >
        <?php foreach($categories as $category): ?>
            <option value="<?php echo $category->getId(); ?>"><?php echo $category->getName(); ?></option>
        <?php endforeach; ?>
    </select>
    <p></p>
    <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
</form>
</body>
</html>