<div class="pure-g">
    <div class="pure-u-1 pure-u-xl-1-5"></div>
    <div class="pure-u-1 pure-u-xl-3-5 main-view">
        <div class="pure-u-1">
            <div class="pure-u-1 gif-list-title-pane">
                <div class="gif-list-title">
                    create account!
                </div>
            </div>
        </div>
        <div class="pure-u-1" style="color: #984B43">
            <p></p>
            <form method="post" class="pure-form pure-form-aligned">
                <fieldset>
                    <div class="pure-control-group">
                        <label for="name" class="pure-input-1-2">username</label>
                        <input id="name" class="pure-input-1-2" type="text" value="<?php echo $name;?>" name="name"  placeholder="Username">
                    </div>
                    <div class="pure-control-group">
                        <label for="email" class="pure-input-1-2">email</label>
                        <input id="email" class="pure-input-1-2" type="email" value="<?php echo $mail;?>" name="email"  placeholder="Email">
                    </div>
                    <div class="pure-control-group">
                        <label for="password" class="pure-input-1-2">password</label>
                        <input id="password" class="pure-input-1-2" type="password" name="pass"  placeholder="Password">
                    </div>
                    <div class="pure-controls">
                        <input id="saveForm" class="pure-button add-button" type="submit" name="submit" value="register!" />
                    </div>

                </fieldset>
            </form>
            <h1 style="color: #984B43;">
                Have an account?
                <a href="/login">Login!</a>
            </h1>
        </div>
        <div class="pure-u-1 pure-u-xl-1-5"></div>
    </div>

</div>